import MetaApi, { SynchronizationListener } from 'metaapi.cloud-sdk';

const SYMBOL='XAUUSD';
const MAGIC=260904;
const INITIAL_SL_PIPS=100;
const TAKE_PROFIT_PIPS=200;
const DIRECTION_CONFIRMATIONS=3;
const MAX_POSITIONS=4;
const EXECUTION_VOLUME=0.01;
const XAUUSD_PIP_SIZE_FALLBACK=0.01;
const HISTORY_SIZE=40;
const FAST_EMA=8;
const SLOW_EMA=21;
const MIN_ENTRY_SPACING_PIPS=35;
const CANDLE_MS=60000;
const MOMENTUM_WINDOW=3;
const CANDLE_HISTORY_SIZE=12;
const LARGE_CANDLE_MULTIPLIER=1.5;
const MIN_LARGE_CANDLE_PIPS=80;
const RETRACEMENT_MIN=0.30;
const RETRACEMENT_MAX=0.70;
const IMPULSE_LOOKBACK_CANDLES=3;
const TRADE_COOLDOWN_MS=3000;
let lastClosureAt=0;
let previousOwnedCount=0;

const $=id=>document.getElementById(id);
const ui={token:$('token'),account:$('account'),price:$('price'),balance:$('balance'),position:$('position'),stop:$('stop'),status:$('status'),save:$('save'),change:$('change'),start:$('start'),stopBot:$('stop')};
let api=null,account=null,connection=null,listener=null;
let trading=false,connecting=false,synchronized=false;
let lastMid=NaN,entryInFlight=false,lastStatus='',lastEntryPrice=NaN;
const priceHistory=[];
const momentumDeltas=[];
const completedCandles=[];
let candleStart=0,candleOpen=NaN,candleHigh=NaN,candleLow=NaN,candleClose=NaN,candleSide='';
let activeImpulse=null;
const reversalCounts=new Map();
let directionCandidate='';
let directionConfirmations=0;

function setStatus(text){if(text!==lastStatus){lastStatus=text;ui.status.textContent=text;}}
function fmt(n){return Number.isFinite(n)?Number(n).toFixed(2):'—';}
function moneyKsh(n){const v=Number(n);return Number.isFinite(v)?`KSh ${v.toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'KSh —';}
function sideOf(x){const t=String(x?.type??'').toUpperCase();return t.includes('BUY')?'BUY':t.includes('SELL')?'SELL':'';}
function isOurs(x){return !!x&&x.symbol===SYMBOL&&(Number(x.magic)===MAGIC||String(x.clientId??'').startsWith('MB_'));}
function idOf(x){return String(x?.id??x?.positionId??x?.orderId??'');}
function volumeOf(x){return Number(x?.volume??0);}
function positionTime(x){const t=Date.parse(String(x?.time??x?.updateTime??''));return Number.isFinite(t)?t:0;}
function normalizeVolume(raw,spec){const min=Number(spec?.minVolume??0.01),max=Number(spec?.maxVolume??100),step=Number(spec?.volumeStep??0.01);let v=Math.max(min,Math.min(max,raw));if(step>0)v=Math.floor(v/step+1e-10)*step;return Number(Math.max(min,v).toFixed(6));}
function brokerPipSize(){const spec=connection?.terminalState?.specification(SYMBOL);const p=Number(spec?.pipSize??spec?.point??0);return p>0?p:XAUUSD_PIP_SIZE_FALLBACK;}
function brokerDigits(){const spec=connection?.terminalState?.specification(SYMBOL);const d=Number(spec?.digits??2);return Number.isFinite(d)?d:2;}
function normalizePrice(price){return Number(Number(price).toFixed(brokerDigits()));}
function currentVolume(){return normalizeVolume(EXECUTION_VOLUME,connection?.terminalState?.specification(SYMBOL)||{minVolume:.01,maxVolume:100,volumeStep:.01});}
function cleanToken(value){return String(value??'').trim().replace(/^Bearer\s+/i,'');}
function validAccountId(value){return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);}
function sdkConstructor(){const Ctor=MetaApi?.default??MetaApi;if(typeof Ctor!=='function')throw new Error('MetaApi browser SDK constructor is unavailable');return Ctor;}
function ema(values,period){if(!values.length)return NaN;const k=2/(period+1);let e=values[0];for(let i=1;i<values.length;i++)e=values[i]*k+e*(1-k);return e;}
function candleRangePips(c){return Math.max(0,(Number(c?.high)-Number(c?.low))/brokerPipSize());}
function candleBodyPips(c){return Math.abs(Number(c?.close)-Number(c?.open))/brokerPipSize();}
function averageCandleRange(){const rows=completedCandles.slice(-CANDLE_HISTORY_SIZE);if(!rows.length)return NaN;return rows.reduce((s,c)=>s+candleRangePips(c),0)/rows.length;}
function finalizeCandle(){if(!Number.isFinite(candleOpen)||!Number.isFinite(candleClose)||!Number.isFinite(candleHigh)||!Number.isFinite(candleLow))return;const candle={open:candleOpen,high:candleHigh,low:candleLow,close:candleClose,start:candleStart,rangePips:candleRangePips({open:candleOpen,high:candleHigh,low:candleLow,close:candleClose}),bodyPips:candleBodyPips({open:candleOpen,close:candleClose})};candle.side=candle.close>candle.open?'BUY':candle.close<candle.open?'SELL':'';candle.avgRangePips=averageCandleRange();completedCandles.push(candle);if(completedCandles.length>CANDLE_HISTORY_SIZE)completedCandles.shift();const avg=candle.avgRangePips;const large=candle.rangePips>=MIN_LARGE_CANDLE_PIPS&&(!Number.isFinite(avg)||candle.rangePips>=avg*LARGE_CANDLE_MULTIPLIER)&&candle.bodyPips>=candle.rangePips*0.55;if(large&&candle.side){activeImpulse={...candle,age:0};setStatus(`LARGE ${candle.side} CANDLE — ${candle.rangePips.toFixed(0)}p impulse; watching retracement`);}else if(activeImpulse)activeImpulse.age++;if(activeImpulse&&activeImpulse.age>IMPULSE_LOOKBACK_CANDLES)activeImpulse=null;}
function updateCandle(mid,previous){const now=Date.now(),start=Math.floor(now/CANDLE_MS)*CANDLE_MS;if(start!==candleStart){if(candleStart)finalizeCandle();candleStart=start;candleOpen=mid;candleHigh=mid;candleLow=mid;candleClose=mid;candleSide='';momentumDeltas.length=0;reversalCounts.clear();}if(!Number.isFinite(candleOpen))candleOpen=mid;if(!Number.isFinite(candleHigh)||mid>candleHigh)candleHigh=mid;if(!Number.isFinite(candleLow)||mid<candleLow)candleLow=mid;candleClose=mid;const delta=Number.isFinite(previous)?mid-previous:0;if(Number.isFinite(delta)){momentumDeltas.push(delta);if(momentumDeltas.length>MOMENTUM_WINDOW)momentumDeltas.shift();}if(mid>candleOpen)candleSide='BUY';else if(mid<candleOpen)candleSide='SELL';}
function retracementSignal(){const impulse=activeImpulse;if(!impulse||impulse.age>IMPULSE_LOOKBACK_CANDLES)return {side:'',score:0,priceInZone:false};const range=Number(impulse.close)-Number(impulse.open);if(!Number.isFinite(range)||range===0)return {side:'',score:0,priceInZone:false};const direction=range>0?'BUY':'SELL';const absRange=Math.abs(range);const close=Number(impulse.close);const retraceLow=direction==='BUY'?close-absRange*RETRACEMENT_MAX:close-absRange*RETRACEMENT_MIN;const retraceHigh=direction==='BUY'?close-absRange*RETRACEMENT_MIN:close+absRange*RETRACEMENT_MAX;const low=Math.min(retraceLow,retraceHigh),high=Math.max(retraceLow,retraceHigh);const price=lastMid;const priceInZone=Number.isFinite(price)&&price>=low&&price<=high;const deltas=momentumDeltas.slice(-MOMENTUM_WINDOW);const momentum=deltas.reduce((a,b)=>a+b,0);const last=Number(deltas[deltas.length-1]||0);const aligned=direction==='BUY'?momentum>0&&last>0:momentum<0&&last<0;const notBreakingImpulse=direction==='BUY'?price>impulse.open:price<impulse.open;const score=(priceInZone?2:0)+(aligned?2:0)+(notBreakingImpulse?1:0)+(candleSide===direction?1:0);return {side:priceInZone&&aligned&&notBreakingImpulse&&score>=5?direction:'',score,priceInZone,impulse,direction,zone:[low,high]};}
function directionSignal(){if(priceHistory.length<SLOW_EMA+8)return {side:'',score:0,confirmed:false,mode:'building'};const mids=priceHistory.map(x=>x.mid);const fastSeries=mids.slice(-FAST_EMA*2),slowSeries=mids.slice(-SLOW_EMA*2);const fast=ema(fastSeries,FAST_EMA),slow=ema(slowSeries,SLOW_EMA);const fastPrev=ema(fastSeries.slice(0,-5),FAST_EMA),slowPrev=ema(slowSeries.slice(0,-5),SLOW_EMA);const fastSlope=fast-fastPrev,slowSlope=slow-slowPrev;const deltas=momentumDeltas.slice(-MOMENTUM_WINDOW),momentum=deltas.reduce((a,b)=>a+b,0),price=mids[mids.length-1];const retrace=retracementSignal();if(retrace.side){directionCandidate=retrace.side;directionConfirmations=DIRECTION_CONFIRMATIONS;return {side:retrace.side,score:retrace.score,confirmed:true,mode:'retracement',impulse:retrace.impulse};}const buyScore=(fast>slow?1:0)+(fastSlope>0?1:0)+(slowSlope>0?1:0)+(momentum>0?1:0)+(candleSide==='BUY'?1:0)+(price>fast?1:0);const sellScore=(fast<slow?1:0)+(fastSlope<0?1:0)+(slowSlope<0?1:0)+(momentum<0?1:0)+(candleSide==='SELL'?1:0)+(price<fast?1:0);let side='';if(buyScore>=4&&buyScore>sellScore)side='BUY';else if(sellScore>=4&&sellScore>buyScore)side='SELL';const score=side==='BUY'?buyScore:side==='SELL'?sellScore:0;if(!side){directionCandidate='';directionConfirmations=0;return {side:'',score,confirmed:false,mode:'trend'};}if(side===directionCandidate)directionConfirmations++;else{directionCandidate=side;directionConfirmations=1;}return {side:directionConfirmations>=DIRECTION_CONFIRMATIONS?side:'',score,confirmed:directionConfirmations>=DIRECTION_CONFIRMATIONS,mode:'trend'};}
function positionDistanceAllows(side,positions){if(!Number.isFinite(lastEntryPrice))return true;const pip=brokerPipSize();const same=[...positions].filter(p=>sideOf(p)===side).sort((a,b)=>positionTime(b)-positionTime(a))[0];const ref=Number(same?.openPrice??lastEntryPrice);return !Number.isFinite(ref)||Math.abs(lastMid-ref)/pip>=MIN_ENTRY_SPACING_PIPS;}
function initialStop(side,price){const pip=brokerPipSize(),base=Number(price);if(!Number.isFinite(base)||base<=0)return undefined;return normalizePrice(side==='BUY'?base-INITIAL_SL_PIPS*pip:base+INITIAL_SL_PIPS*pip);}
function momentumFaded(side){if(candleSide!==side||momentumDeltas.length<MOMENTUM_WINDOW)return false;const sum=momentumDeltas.reduce((a,b)=>a+b,0);return side==='BUY'?sum<=0:sum>=0;}
function updateProfitLossUI(){const info=connection?.terminalState?.accountInformation;const positions=ownedPositions();const rawBal=Number(info?.balance),rawEq=Number(info?.equity),rawMargin=Number(info?.margin);const pnl=positions.reduce((s,x)=>s+(Number(x.profit)||0),0);if(Number.isFinite(rawBal)){ui.balance.textContent=moneyKsh(rawBal);$('pnlBalance').textContent=moneyKsh(rawBal);$('livePnl').textContent=moneyKsh(pnl);$('floatingPnl').textContent=moneyKsh(pnl);$('pnlPercent').textContent=`${rawBal?((pnl/rawBal)*100).toFixed(2):'0.00'}%`;}else{ui.balance.textContent='KSh —';$('pnlBalance').textContent='KSh —';$('livePnl').textContent='KSh 0.00';$('floatingPnl').textContent='KSh 0.00';$('pnlPercent').textContent='0.00%';}if(Number.isFinite(rawEq)){$('equity').textContent=moneyKsh(rawEq);$('pnlEquity').textContent=moneyKsh(rawEq);}else{$('equity').textContent='KSh —';$('pnlEquity').textContent='KSh —';}if(Number.isFinite(rawMargin))$('margin').textContent=moneyKsh(rawMargin);else $('margin').textContent='KSh —';}

class BotListener extends SynchronizationListener{
 onConnected(){setStatus('MetaApi connected — synchronizing…');}
 onDisconnected(){synchronized=false;setStatus('MetaApi disconnected — waiting to reconnect…');}
 onSynchronizationStarted(){synchronized=false;setStatus('Synchronizing MetaApi terminal…');}
 onSynchronizationFinished(){synchronized=true;setStatus('CONNECTED — XAUUSD live stream active');reconcile();}
 onSymbolPricesUpdated(instanceIndex,prices){const p=Array.isArray(prices)?prices.find(x=>x?.symbol===SYMBOL):(prices?.symbol===SYMBOL?prices:null);if(!p)return;const bid=Number(p.bid),ask=Number(p.ask);if(!Number.isFinite(bid)||!Number.isFinite(ask)||bid<=0||ask<=0||ask<bid)return;const mid=(bid+ask)/2,previous=lastMid;lastMid=mid;updateCandle(mid,previous);priceHistory.push({mid,bid,ask,time:Date.now()});if(priceHistory.length>HISTORY_SIZE)priceHistory.shift();ui.price.textContent=fmt(mid);updateProfitLossUI();if(trading&&synchronized)void onTick(mid,bid,ask,previous);}
 onPositionUpdated(instanceIndex,position){if(position?.symbol===SYMBOL)reconcile();}
 onPositionRemoved(){reconcile();}
 onOrderUpdated(instanceIndex,order){if(order?.symbol===SYMBOL)reconcile();}
 onOrderCompleted(){reconcile();}
 onOrderFailed(instanceIndex,orderId,error){setStatus(`Order failed: ${error?.message||error}`);reconcile();}
}
async function connectSdk(){if(connecting||connection)return;const token=cleanToken(ui.token.value),accountId=ui.account.value.trim();if(!token||token==='SAVED TOKEN'){setStatus('MetaAPI token is missing');return;}if(!accountId){setStatus('MetaAPI account ID is missing');return;}if(!validAccountId(accountId)){setStatus('MetaAPI account ID format is invalid');return;}connecting=true;setStatus('Connecting directly to MetaApi…');try{const MetaApiClass=sdkConstructor();api=new MetaApiClass(token);account=await api.metatraderAccountApi.getAccount(accountId);if(!account?.id)throw new Error('MetaApi account not found');if(typeof account.waitConnected==='function')await account.waitConnected();connection=account.getStreamingConnection();listener=new BotListener();connection.addSynchronizationListener(listener);await connection.connect();await connection.waitSynchronized();synchronized=true;await connection.subscribeToMarketData(SYMBOL);reconcile();setStatus('CONNECTED — XAUUSD live stream active');}catch(e){const msg=e?.message||String(e);try{await connection?.close();}catch(_){}try{await api?.close();}catch(_){}connection=null;account=null;api=null;synchronized=false;setStatus(`MetaAPI connection failed: ${msg}`);}finally{connecting=false;}}
function ownedPositions(){return(connection?.terminalState?.positions||[]).filter(isOurs);}
function reconcile(){if(!connection?.terminalState)return;const positions=ownedPositions();const latest=[...positions].sort((a,b)=>positionTime(b)-positionTime(a))[0]||null;if(previousOwnedCount>0&&positions.length===0){lastClosureAt=Date.now();setStatus('ALL POSITIONS CLOSED — 3s COOL-OFF before next batch');}previousOwnedCount=positions.length;ui.position.textContent=positions.length?(positions.length===1?sideOf(latest):`${positions.length}/4 ${sideOf(latest)}`):'—';updateProfitLossUI();}
async function closePosition(position,reason){const id=idOf(position);if(!id||!connection)return;try{await connection.closePosition(id);setStatus(`CLOSE ${sideOf(position)} — ${reason}`);}catch(e){setStatus(`Close failed: ${e?.message||e}`);}}
async function closeOurs(reason){const positions=ownedPositions();if(!positions.length)return;await Promise.all(positions.map(p=>closePosition(p,reason)));lastClosureAt=Date.now();setStatus('ALL POSITIONS CLOSE REQUESTS SENT — 3s COOL-OFF');}
async function enter(side,bid,ask){const positions=ownedPositions();if(entryInFlight||positions.length>=MAX_POSITIONS||!connection||!synchronized||!positionDistanceAllows(side,positions))return;if(Date.now()-lastClosureAt<TRADE_COOLDOWN_MS){const left=TRADE_COOLDOWN_MS-(Date.now()-lastClosureAt);setStatus(`COOL-OFF ${left}ms before next batch`);return;}const slots=Math.max(0,MAX_POSITIONS-positions.length);if(!slots)return;const volume=currentVolume(),reference=side==='BUY'?ask:bid,stopLoss=initialStop(side,reference);if(!Number.isFinite(stopLoss))return;entryInFlight=true;try{const orders=[];for(let i=0;i<slots;i++){const clientId=`MB_${Date.now().toString(36)}_${i}_${Math.floor(Math.random()*36).toString(36)}`,options={comment:`MB ${side}`,magic:MAGIC,clientId};orders.push(side==='BUY'?connection.createMarketBuyOrder(SYMBOL,volume,stopLoss,normalizePrice(reference+TAKE_PROFIT_PIPS*brokerPipSize()),options):connection.createMarketSellOrder(SYMBOL,volume,stopLoss,normalizePrice(reference-TAKE_PROFIT_PIPS*brokerPipSize()),options));}await Promise.all(orders);lastEntryPrice=reference;setStatus(`OPEN BATCH ${side} ${slots} × ${volume} — SL ${INITIAL_SL_PIPS}p | TP ${TAKE_PROFIT_PIPS}p`);await waitForPosition(side,5000);reconcile();}catch(e){setStatus(`Batch entry failed: ${e?.message||e}`);}finally{entryInFlight=false;}}
async function waitForPosition(side,timeoutMs){const end=Date.now()+timeoutMs;while(Date.now()<end){reconcile();const p=ownedPositions().find(x=>sideOf(x)===side);if(p){lastEntryPrice=Number(p.openPrice)||lastEntryPrice;return p;}await new Promise(r=>setTimeout(r,100));}return null;}
async function onTick(mid,bid,ask,previous){reconcile();if(Number.isNaN(previous)){setStatus('Streaming XAUUSD — building momentum + candle model');return;}const positions=ownedPositions();if(positions.length){const heldSide=sideOf(positions[0]);reversalCounts.delete(heldSide);setStatus(`HOLDING ${positions.length}/${MAX_POSITIONS} ${heldSide} | momentum + candle structure active`);if(positions.length>=MAX_POSITIONS)return;}const signal=directionSignal();if(!signal.side){if(!positions.length){const r=retracementSignal();setStatus(r.priceInZone?`RETRACEMENT — waiting for ${r.direction} momentum confirmation`:`WAITING — momentum/candle direction | samples ${priceHistory.length}/${SLOW_EMA+2}`);}return;}if(positions.length&&positions.some(p=>sideOf(p)!==signal.side))return;await enter(signal.side,bid,ask);}
function startForegroundService(){try{if(window.AndroidBot?.startForegroundBot)window.AndroidBot.startForegroundBot();}catch(_) {}}
function stopForegroundService(){try{if(window.AndroidBot?.stopForegroundBot)window.AndroidBot.stopForegroundBot();}catch(_) {}}
function saveCredentials(){const token=cleanToken(ui.token.value),accountId=ui.account.value.trim();if(!token||token==='SAVED TOKEN'){setStatus('Enter a valid MetaAPI token');return;}if(!validAccountId(accountId)){setStatus('Enter a valid MetaAPI account ID');return;}localStorage.setItem('metaapi.token',token);localStorage.setItem('metaapi.accountId',accountId);ui.token.value='SAVED TOKEN';ui.token.disabled=true;ui.token.value=token;connectSdk().finally(()=>{ui.token.value='SAVED TOKEN';ui.token.disabled=true;});}
function changeCredentials(){trading=false;stopForegroundService();localStorage.removeItem('metaapi.token');localStorage.removeItem('metaapi.accountId');if(connection)connection.close().catch(()=>{});if(api)api.close().catch(()=>{});connection=null;account=null;api=null;synchronized=false;ui.token.disabled=false;ui.token.value='';ui.account.value='';priceHistory.length=0;momentumDeltas.length=0;completedCandles.length=0;activeImpulse=null;lastEntryPrice=NaN;candleStart=0;candleOpen=NaN;candleHigh=NaN;candleLow=NaN;candleClose=NaN;candleSide='';reversalCounts.clear();setStatus('Enter new MetaAPI credentials');}
function startBot(){if(!connection||!synchronized){setStatus('Connect MetaApi first');return;}startForegroundService();trading=true;setStatus('BOT RUNNING — momentum + large-candle retracement entries');}
function stopBot(){trading=false;stopForegroundService();setStatus('BOT STOPPED');}
ui.save.onclick=saveCredentials;ui.change.onclick=changeCredentials;ui.start.onclick=startBot;ui.stopBot.onclick=stopBot;

function showNavView(view){const nav=[...document.querySelectorAll('.nav div')];nav.forEach((el,i)=>el.classList.toggle('active',i===view));let panel=$('navPanel');if(!panel){panel=document.createElement('section');panel.id='navPanel';panel.className='card';const navEl=document.querySelector('.nav');navEl?.parentNode.insertBefore(panel,navEl);}let html='';if(view===0){panel.style.display='none';window.scrollTo({top:0,behavior:'smooth'});return;}if(view===1){panel.style.display='block';html='<div class="section-title"><span>Trades</span><span class="cyan">LIVE</span></div><div id="navTrades">Loading live positions…</div>';panel.innerHTML=html;const refresh=()=>{const ps=ownedPositions();const el=$('navTrades');if(!el)return;if(!ps.length){el.innerHTML='<div class="status"><i></i><div>No active Pips-life positions.</div></div>';return;}el.innerHTML=ps.map((p,i)=>{const side=sideOf(p),profit=Number(p.profit)||0,open=Number(p.openPrice),sl=Number(p.stopLoss);return `<div class="metric" style="margin:6px 0"><small>Position ${i+1} • ${side}</small><strong class="${profit>=0?'green':'red'}">${moneyKsh(profit)}</strong><div class="subline">Open ${fmt(open)} • Trailing SL ${fmt(sl)} • ${volumeOf(p)} lot</div></div>`}).join('');};refresh();panel._navTimer&&clearInterval(panel._navTimer);panel._navTimer=setInterval(refresh,1000);}if(view===2){panel.style.display='block';panel.innerHTML='<div class="section-title"><span>History</span><span class="cyan">SESSION</span></div><div class="status"><i></i><div>Closed-position history is maintained by MetaApi. Use the MetaApi account history to review completed trades; this view stays available for the live session.</div></div>';}if(view===3){panel.style.display='block';panel.innerHTML=`<div class="section-title"><span>Logs</span><span class="cyan">LIVE ENGINE</span></div><div class="status"><i></i><div>${lastStatus||'Waiting for engine events…'}</div></div><div class="subline" style="margin-top:10px">Connection: ${connection?'CONNECTED':'DISCONNECTED'} • Synchronization: ${synchronized?'READY':'WAITING'} • Bot: ${trading?'RUNNING':'STOPPED'} • XAUUSD price: ${fmt(lastMid)}</div>`;}window.scrollTo({top:Math.max(0,panel.offsetTop-20),behavior:'smooth'});}
document.querySelectorAll('.nav div').forEach((el,i)=>el.addEventListener('click',()=>showNavView(i)));

const savedToken=cleanToken(localStorage.getItem('metaapi.token')),savedAccount=String(localStorage.getItem('metaapi.accountId')||'').trim();
if(savedToken&&savedAccount){ui.token.value=savedToken;ui.account.value=savedAccount;connectSdk().finally(()=>{ui.token.value='SAVED TOKEN';ui.token.disabled=true;});}
