import MetaApi, { SynchronizationListener } from 'metaapi.cloud-sdk';

const SYMBOL='XAUUSD';
const MAGIC=260903;
const TRAIL_PIPS=70;
const EXECUTION_VOLUME=0.01;
const XAUUSD_PIP_SIZE_FALLBACK=0.01;
const CANDLE_TIMEFRAME='1m';
const CANDLE_BUFFER=36;
// Fast volatility response: no candle/range/noise gate.
const MIN_VELOCITY_PIPS=0.10;
const ENTRY_COOLDOWN_MS=1000;
const REVERSAL_CONFIRM=2;

const $=id=>document.getElementById(id);
const ui={token:$('token'),account:$('account'),price:$('price'),balance:$('balance'),position:$('position'),stop:$('stop'),winRate:$('winRate'),status:$('status'),save:$('save'),change:$('change'),start:$('start'),stopBot:$('stop')};
let api=null,account=null,connection=null,listener=null;
let trading=false,stopRequested=false,connecting=false,synchronized=false,hasSynchronized=false;
let reconnectTimer=null,reconnectAttempt=0;
let lastMid=NaN,lastBid=NaN,lastAsk=NaN,lastEntryAt=0;
let positions=[];
const positionStops=new Map();
const stopActions=new Set();
let entryInFlight=false,reconcileInFlight=false;
let lastDirection='',marketBias='',pullbackActive=false;
let candles=[];
const eventLog=[],sessionHistory=[];
let lastStatus='';
let tradeStats=loadTradeStats();

function loadTradeStats(){try{const x=JSON.parse(localStorage.getItem('pipslife.tradeStats')||'{}');return {wins:Number(x.wins)||0,losses:Number(x.losses)||0};}catch(_){return {wins:0,losses:0};}}
function saveTradeStats(){localStorage.setItem('pipslife.tradeStats',JSON.stringify(tradeStats));}
function winRate(){const total=tradeStats.wins+tradeStats.losses;return total>0?(tradeStats.wins/total)*100:0;}
function renderWinRate(){if(ui.winRate)ui.winRate.textContent=(tradeStats.wins+tradeStats.losses)>0?`${winRate().toFixed(1)}%`:'—';}
function recordClosedPosition(position){const profit=Number(position?.profit??0)+Number(position?.swap??0)+Number(position?.commission??0);if(!Number.isFinite(profit)||!idOf(position))return; if(profit>0)tradeStats.wins++;else if(profit<0)tradeStats.losses++;else return;saveTradeStats();sessionHistory.unshift({time:Date.now(),text:`Closed ${sideOf(position)} ${profit>0?'WIN':'LOSS'} ${profit.toFixed(2)}`});renderWinRate();}
function addLog(text){const now=new Date();eventLog.unshift({time:now,text:String(text)});if(eventLog.length>60)eventLog.pop();renderLogs();}
function setStatus(text){const value=String(text);if(value!==lastStatus){lastStatus=value;ui.status.textContent=value;addLog(value);}else ui.status.textContent=value;renderPageData();}
function fmt(n){return Number.isFinite(n)?Number(n).toFixed(2):'—';}
function sideOf(x){const t=String(x?.type??'').toUpperCase();return t.includes('BUY')?'BUY':t.includes('SELL')?'SELL':'';}
function isOurs(x){return !!x&&x.symbol===SYMBOL&&(Number(x.magic)===MAGIC||String(x.clientId??'').startsWith('MB_'));}
function idOf(x){return String(x?.id??x?.positionId??x?.orderId??'');}
function volumeOf(x){return Number(x?.volume??0);}
function normalizeVolume(raw,spec){const min=Number(spec?.minVolume??0.01),max=Number(spec?.maxVolume??100),step=Number(spec?.volumeStep??0.01);let v=Math.max(min,Math.min(max,raw));if(step>0)v=Math.floor(v/step+1e-10)*step;return Number(Math.max(min,v).toFixed(6));}
function brokerPipSize(){const spec=connection?.terminalState?.specification(SYMBOL);const p=Number(spec?.pipSize??spec?.point??0);return p>0?p:XAUUSD_PIP_SIZE_FALLBACK;}
function brokerDigits(){const spec=connection?.terminalState?.specification(SYMBOL);const d=Number(spec?.digits??2);return Number.isFinite(d)?d:2;}
function normalizePrice(price){return Number(Number(price).toFixed(brokerDigits()));}
function currentVolume(){return normalizeVolume(EXECUTION_VOLUME,connection?.terminalState?.specification(SYMBOL)||{minVolume:.01,maxVolume:100,volumeStep:.01});}
function cleanToken(value){return String(value??'').trim().replace(/^Bearer\s+/i,'');}
function validAccountId(value){return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);}
function sdkConstructor(){const Ctor=MetaApi?.default??MetaApi;if(typeof Ctor!=='function')throw new Error('MetaApi browser SDK constructor is unavailable');return Ctor;}
function credentialToken(){return cleanToken(ui.token.value)==='SAVED TOKEN'?cleanToken(localStorage.getItem('metaapi.token')):cleanToken(ui.token.value);}
function credentialAccount(){return String(ui.account.value||localStorage.getItem('metaapi.accountId')||'').trim();}
function persistCredentials(token,accountId){localStorage.setItem('metaapi.token',token);localStorage.setItem('metaapi.accountId',accountId);try{window.AndroidBot?.saveCredentials?.(accountId,token);}catch(e){addLog(`Secure credential store unavailable: ${e?.message||e}`);}}
function clearPersistedCredentials(){localStorage.removeItem('metaapi.token');localStorage.removeItem('metaapi.accountId');try{window.AndroidBot?.clearCredentials?.();}catch(_) {}}
function positionList(){return positions.slice().sort((a,b)=>idOf(a).localeCompare(idOf(b)));}
function candleTime(c){const t=c?.time instanceof Date?c.time:new Date(c?.time);return t.getTime();}
function normalizeCandles(list){return (Array.isArray(list)?list:[]).filter(c=>Number.isFinite(Number(c?.open))&&Number.isFinite(Number(c?.high))&&Number.isFinite(Number(c?.low))&&Number.isFinite(Number(c?.close))&&Number.isFinite(candleTime(c))).sort((a,b)=>candleTime(a)-candleTime(b)).slice(-CANDLE_BUFFER);}
function closedCandles(){if(candles.length<3)return candles.slice();return candles.slice(0,-1);}
function updateBias(){const cs=closedCandles();if(cs.length<6)return marketBias;const recent=cs.slice(-12),closes=recent.map(c=>Number(c.close));const fast=closes.slice(-5).reduce((a,b)=>a+b,0)/Math.min(5,closes.length),slow=closes.reduce((a,b)=>a+b,0)/closes.length;const last=recent.at(-1),prev=recent.at(-2);const bullishStructure=last.close>prev.close&&last.high>=prev.high&&last.low>=prev.low;const bearishStructure=last.close<prev.close&&last.low<=prev.low&&last.high<=prev.high;const bullScore=(fast>slow?1:0)+(last.close>recent[0].close?1:0)+(bullishStructure?1:0);const bearScore=(fast<slow?1:0)+(last.close<recent[0].close?1:0)+(bearishStructure?1:0);const old=marketBias;if(bullScore>=2&&bullScore>bearScore)marketBias='BUY';else if(bearScore>=2&&bearScore>bullScore)marketBias='SELL';if(old&&marketBias!==old)addLog(`BIAS CHANGED ${old} → ${marketBias}`);return marketBias;}
function structureLevels(){const cs=closedCandles().slice(-8);if(!cs.length)return {low:NaN,high:NaN};return {low:Math.min(...cs.map(c=>Number(c.low))),high:Math.max(...cs.map(c=>Number(c.high)))};}
function reversalConfirmed(side,price){const cs=closedCandles();if(cs.length<REVERSAL_CONFIRM)return false;const last=cs.at(-1),prev=cs.at(-2),levels=structureLevels();if(side==='BUY'){const bearishCandles=Number(last.close)<Number(last.open)&&Number(prev.close)<Number(prev.open);return price<levels.low||(bearishCandles&&Number(last.close)<Number(prev.low));}const bullishCandles=Number(last.close)>Number(last.open)&&Number(prev.close)>Number(prev.open);return price>levels.high||(bullishCandles&&Number(last.close)>Number(prev.high));}
function directionalVelocity(side,mid,reference){if(!Number.isFinite(reference)||!Number.isFinite(mid))return false;const delta=(mid-reference)/brokerPipSize();return side==='BUY'?delta>=MIN_VELOCITY_PIPS:delta<=-MIN_VELOCITY_PIPS;}
function evaluateMarket(mid,previous){updateBias();if(!marketBias)return {action:'WAIT',reason:'building candle bias'};if(reversalConfirmed(marketBias,mid)){const old=marketBias;marketBias=old==='BUY'?'SELL':'BUY';pullbackActive=false;addLog(`DIRECTION CHANGE CONFIRMED — ${old} → ${marketBias}`);return {action:'BIAS_CHANGED',reason:'market structure broken'};}const against=marketBias==='BUY'?mid<previous:mid>previous;if(against){pullbackActive=true;return {action:'PULLBACK',reason:`${marketBias} bias retained`};}if(pullbackActive&&directionalVelocity(marketBias,mid,previous)){pullbackActive=false;return {action:'ENTRY',side:marketBias,reason:'pullback resumed with velocity'};}if(!pullbackActive&&directionalVelocity(marketBias,mid,previous))return {action:'ENTRY',side:marketBias,reason:'velocity expansion'};return {action:'WAIT',reason:`${marketBias} bias`};}
function dynamicTrailPips(position,bid,ask){const side=sideOf(position),entry=Number(position.openPrice),spot=side==='BUY'?bid:ask,pip=brokerPipSize();if(!Number.isFinite(entry)||!Number.isFinite(spot)||!pip)return TRAIL_PIPS;const profit=side==='BUY'?(spot-entry)/pip:(entry-spot)/pip;if(profit>=400)return 120;if(profit>=250)return 100;return TRAIL_PIPS;}
function stopCandidate(position,bid,ask){const side=sideOf(position),spot=side==='BUY'?bid:ask;return normalizePrice(side==='BUY'?spot-dynamicTrailPips(position,bid,ask)*brokerPipSize():spot+dynamicTrailPips(position,bid,ask)*brokerPipSize());}

class BotListener extends SynchronizationListener{
  async onConnected(){reconnectAttempt=0;setStatus(hasSynchronized?'MetaApi connection healthy — sync refresh handled in background':'MetaApi connected — initial synchronization…');}
  async onDisconnected(){synchronized=false;hasSynchronized=false;setStatus('MetaApi disconnected — reconnecting automatically…');scheduleReconnect();}
  async onSynchronizationStarted(){if(!hasSynchronized){synchronized=false;setStatus('MetaApi initial synchronization…');}else{addLog('MetaApi synchronization refresh detected — keeping live trading state active');}}
  async onSynchronizationFinished(){synchronized=true;hasSynchronized=true;reconnectAttempt=0;clearTimeout(reconnectTimer);reconnectTimer=null;setStatus(`CONNECTED — ${SYMBOL} live stream active — bias ${marketBias||'CALCULATING'}`);void reconcile();}
  async onSymbolPricesUpdated(instanceIndex,prices){const p=Array.isArray(prices)?prices.find(x=>x?.symbol===SYMBOL):(prices?.symbol===SYMBOL?prices:null);if(!p)return;const bid=Number(p.bid),ask=Number(p.ask);if(!Number.isFinite(bid)||!Number.isFinite(ask))return;const mid=(bid+ask)/2;lastBid=bid;lastAsk=ask;ui.price.textContent=fmt(mid);const info=connection?.terminalState?.accountInformation;if(info?.balance!=null)ui.balance.textContent=fmt(Number(info.balance));if(!trading||stopRequested||!synchronized){lastMid=mid;renderPageData();return;}await onTick(mid,bid,ask);}
  async onCandlesUpdated(instanceIndex,updates){const incoming=Array.isArray(updates)?updates.filter(x=>x?.symbol===SYMBOL):[];if(incoming.length){candles=normalizeCandles([...candles,...incoming]);const old=marketBias;updateBias();if(old!==marketBias&&old)addLog(`CANDLE BIAS ${old} → ${marketBias}`);renderPageData();}}
  async onPositionUpdated(instanceIndex,position){if(position?.symbol===SYMBOL)void reconcile();}
  async onPositionRemoved(instanceIndex,positionId){if(positionId){positionStops.delete(String(positionId));stopActions.delete(String(positionId));}void reconcile();}
  async onOrderUpdated(instanceIndex,order){if(order?.symbol===SYMBOL)void reconcile();}
  async onOrderCompleted(instanceIndex,order){if(order?.symbol===SYMBOL)void reconcile();}
  async onOrderFailed(instanceIndex,orderId,error){setStatus(`Order failed: ${error?.message||error}`);void reconcile();}
}
async function loadCandleContext(){try{if(typeof account?.getHistoricalCandles==='function'){const hist=await account.getHistoricalCandles(SYMBOL,CANDLE_TIMEFRAME);if(Array.isArray(hist)&&hist.length)candles=normalizeCandles(hist);}}catch(e){addLog(`Historical candle context unavailable — live candle stream will build bias: ${e?.message||e}`);}updateBias();}
async function connectSdk(force=false){if(connecting)return;const token=credentialToken(),accountId=credentialAccount();if(!token||token==='SAVED TOKEN'){setStatus('MetaAPI token is missing');return;}if(!accountId){setStatus('MetaAPI account ID is missing');return;}if(!validAccountId(accountId)){setStatus('MetaAPI account ID format is invalid');return;}if(connection&&!force)return;connecting=true;setStatus(force?'Reconnecting MetaApi…':'Connecting directly to MetaApi…');try{if(force&&connection){try{connection.removeSynchronizationListener?.(listener);}catch(_){}try{await connection.close();}catch(_){}connection=null;}const MetaApiClass=sdkConstructor();api=new MetaApiClass(token);account=await api.metatraderAccountApi.getAccount(accountId);if(!account?.id)throw new Error('MetaApi account not found');if(account.state!=='DEPLOYED'){setStatus('Deploying MetaApi account…');await account.deploy();}if(typeof account.waitConnected==='function')await account.waitConnected();await loadCandleContext();connection=account.getStreamingConnection();listener=new BotListener();connection.addSynchronizationListener(listener);await connection.connect();await connection.waitSynchronized();synchronized=true;hasSynchronized=true;reconnectAttempt=0;await connection.subscribeToMarketData(SYMBOL,[{type:'quotes',intervalInMilliseconds:1000},{type:'candles',timeframe:CANDLE_TIMEFRAME,intervalInMilliseconds:1000},{type:'ticks'}]);void reconcile();setStatus(`CONNECTED — ${SYMBOL} live tick/candle stream active — bias ${marketBias||'CALCULATING'}`);}catch(e){const msg=e?.message||String(e);try{await connection?.close();}catch(_){}try{await api?.close();}catch(_){}connection=null;account=null;api=null;synchronized=false;hasSynchronized=false;setStatus(`MetaApi connection failed: ${msg}`);scheduleReconnect();}finally{connecting=false;renderPageData();}}
function scheduleReconnect(){if(stopRequested)return;const token=credentialToken(),accountId=credentialAccount();if(!token||!accountId)return;clearTimeout(reconnectTimer);const delay=Math.min(30000,1000*Math.pow(2,reconnectAttempt++));reconnectTimer=setTimeout(()=>void connectSdk(true),delay);addLog(`Reconnect scheduled in ${Math.round(delay/1000)}s`);}
async function reconcile(){if(reconcileInFlight||!connection?.terminalState)return;reconcileInFlight=true;try{const state=connection.terminalState;const live=(state.positions||[]).filter(isOurs);const liveIds=new Set(live.map(idOf));const liveMap=new Map(live.map(p=>[idOf(p),p]));for(const old of positions){const id=idOf(old);if(id&&!liveMap.has(id))recordClosedPosition(old);}for(const id of [...positionStops.keys()])if(!liveIds.has(id))positionStops.delete(id);for(const id of [...stopActions])if(!liveIds.has(id))stopActions.delete(id);const staleStops=(state.orders||[]).filter(isOurs).filter(o=>String(o.type??'').toUpperCase().includes('STOP'));for(const o of staleStops)void cancelOrder(idOf(o));positions=live;for(const p of positions){const id=idOf(p),stopPrice=Number(p.stopLoss??0);positionStops.set(id,stopPrice>0?stopPrice:positionStops.get(id)||0);if(sideOf(p)&&!stopPrice&&!stopActions.has(id))void setInitialStop(p);}const first=positionList()[0]||null;ui.position.textContent=positions.length?(positions.length===1?sideOf(first):`${positions.length} OPEN`):'—';ui.stop.textContent=first&&Number(positionStops.get(idOf(first))||first.stopLoss||0)>0?fmt(Number(positionStops.get(idOf(first))||first.stopLoss)):'—';renderPageData();}finally{reconcileInFlight=false;}}

// MetaApi clientId must be exactly strategyId_positionId_orderId.
// Each component must be a single alphanumeric token. The previous value
// used an underscore inside orderId, causing MetaApi schema validation to fail.
function tradeOptions(side){const orderId=`${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;return{comment:side==='BUY'?'MB_BUY':'MB_SELL',clientId:`MB_${side[0]}_${orderId}`,magic:MAGIC};}
async function enter(side,spot){if(entryInFlight||!connection||!trading||stopRequested||!synchronized)return;if(Date.now()-lastEntryAt<ENTRY_COOLDOWN_MS)return;const volume=currentVolume();if(volume<=0){setStatus('ENTRY BLOCKED — invalid XAUUSD execution volume');return;}if(!Number.isFinite(Number(spot))||Number(spot)<=0){setStatus('ENTRY BLOCKED — invalid live XAUUSD price');return;}entryInFlight=true;try{const options=tradeOptions(side);if(stopRequested||!trading)return;if(side==='BUY')await connection.createMarketBuyOrder(SYMBOL,volume,undefined,undefined,options);else await connection.createMarketSellOrder(SYMBOL,volume,undefined,undefined,options);lastEntryAt=Date.now();lastDirection=side;if(stopRequested||!trading){await reconcile();const newest=positionList().find(p=>sideOf(p)===side);if(newest)await closePositionSafe(newest);return;}setStatus(`OPEN ${side} ${volume} — applying independent protection`);await waitForNewPosition(side,3000);await reconcile();}catch(e){if(!stopRequested)setStatus(`Entry failed: ${e?.message||e}`);}finally{entryInFlight=false;}}
async function waitForNewPosition(side,timeoutMs){const end=Date.now()+timeoutMs;while(Date.now()<end){await reconcile();const p=positionList().find(x=>sideOf(x)===side&&Number(positionStops.get(idOf(x))||x.stopLoss||0)<=0);if(p){await setInitialStop(p);return p;}await new Promise(r=>setTimeout(r,50));}return null;}
async function setInitialStop(position){const id=idOf(position);if(!id||stopActions.has(id)||!connection||stopRequested)return;const side=sideOf(position),spot=side==='BUY'?Number(lastBid):Number(lastAsk);if(!Number.isFinite(spot))return;const candidate=normalizePrice(side==='BUY'?spot-TRAIL_PIPS*brokerPipSize():spot+TRAIL_PIPS*brokerPipSize());if(!Number.isFinite(candidate)||candidate<=0)return;stopActions.add(id);try{await connection.modifyPosition(id,candidate,undefined);positionStops.set(id,candidate);const live=positions.find(p=>idOf(p)===id);if(live)live.stopLoss=candidate;ui.stop.textContent=fmt(candidate);}catch(e){if(!stopRequested)setStatus(`Initial SL failed for ${id}: ${e?.message||e}`);}finally{stopActions.delete(id);}}
async function trailPosition(position,bid,ask){const id=idOf(position);if(!id||stopActions.has(id)||stopRequested||!connection)return;const side=sideOf(position),candidate=stopCandidate(position,bid,ask),existing=Number(position.stopLoss??positionStops.get(id)??0),improve=side==='BUY'?candidate>existing:candidate<existing;if(!Number.isFinite(candidate)||candidate<=0||(existing>0&&!improve))return;stopActions.add(id);try{await connection.modifyPosition(id,candidate,undefined);positionStops.set(id,candidate);position.stopLoss=candidate;}catch(e){if(!stopRequested)addLog(`SL trail failed for ${id}: ${e?.message||e}`);}finally{stopActions.delete(id);}}
async function closeOnMomentumReversal(position,bid,ask){const side=sideOf(position),price=side==='BUY'?bid:ask;if(!reversalConfirmed(side,price))return false;await closePositionSafe(position);addLog(`MOMENTUM EXIT ${side} ${idOf(position)} — confirmed direction reversal`);return true;}
async function manageOpenPositions(bid,ask){const live=positionList();if(!live.length)return;await Promise.all(live.map(async p=>{if(await closeOnMomentumReversal(p,bid,ask))return;await trailPosition(p,bid,ask);}));await reconcile();}
async function trailAll(bid,ask){await manageOpenPositions(bid,ask);}
async function onTick(mid,bid,ask){if(!trading||stopRequested||!synchronized)return;const previous=lastMid;if(positions.length){lastMid=mid;await trailAll(bid,ask);return;}if(!Number.isFinite(previous)||mid===previous){lastMid=mid;return;}const decision=evaluateMarket(mid,previous);lastMid=mid;if(decision.action==='PULLBACK'){lastDirection=marketBias;setStatus(`PULLBACK — ${marketBias} bias retained — watching volatility`);return;}if(decision.action==='BIAS_CHANGED'){lastDirection=marketBias;setStatus(`BIAS CHANGED — now ${marketBias} — watching for aligned velocity`);return;}if(decision.action==='ENTRY'){lastDirection=decision.side;setStatus(`VELOCITY ${decision.side} — ${decision.reason} — executing`);await enter(decision.side,decision.side==='BUY'?ask:bid);}}
async function cancelOrder(id){if(id&&connection){try{await connection.cancelOrder(id);}catch(_) {}}}
async function closePositionSafe(position){if(!position||!connection)return false;try{await connection.closePosition(idOf(position));return true;}catch(e){addLog(`Close position ${idOf(position)} failed: ${e?.message||e}`);return false;}}
async function stopAllTrading(){stopRequested=true;trading=false;clearTimeout(reconnectTimer);reconnectTimer=null;ui.stopBot.classList.add('active');ui.start.classList.remove('active');try{window.AndroidBot?.stopForegroundBot?.();}catch(_){}setStatus('STOPPING — closing all Pips-life positions and cancelling orders…');try{const live=(connection?.terminalState?.positions||[]).filter(isOurs),orders=(connection?.terminalState?.orders||[]).filter(isOurs);await Promise.all(orders.map(o=>cancelOrder(idOf(o))));await Promise.all(live.map(p=>closePositionSafe(p)));await new Promise(r=>setTimeout(r,300));await reconcile();positions=[];positionStops.clear();stopActions.clear();ui.position.textContent='—';ui.stop.textContent='—';setStatus('BOT STOPPED — all Pips-life positions closed; new orders disabled');sessionHistory.unshift({time:Date.now(),text:'Bot stopped — positions closed and orders disabled'});}catch(e){setStatus(`BOT STOP ERROR — ${e?.message||e}`);}}
function saveCredentials(){const token=cleanToken(ui.token.value),accountId=ui.account.value.trim();if(!token||token==='SAVED TOKEN'){setStatus('Enter a valid MetaAPI token');return;}if(!validAccountId(accountId)){setStatus('Enter a valid MetaAPI account ID');return;}persistCredentials(token,accountId);ui.token.value='SAVED TOKEN';ui.token.disabled=true;addLog('Credentials saved locally — encrypted Android store + WebView fallback');void connectSdk();}
function changeCredentials(){void stopAllTrading();clearPersistedCredentials();try{connection?.close();api?.close();}catch(_){}connection=null;account=null;api=null;synchronized=false;hasSynchronized=false;positions=[];positionStops.clear();stopActions.clear();ui.token.disabled=false;ui.token.value='';ui.account.value='';setStatus('Enter new MetaAPI credentials');}
function startBot(){stopRequested=false;if(!connection||!synchronized){setStatus('START BLOCKED — Connect MetaApi first');return;}trading=true;try{window.AndroidBot?.startForegroundBot?.();}catch(_){}ui.start.classList.add('active');ui.stopBot.classList.remove('active');setStatus(`BOT RUNNING — VOLATILITY EXECUTION + BIAS + ADAPTIVE TRAILS`);addLog('BOT STARTED — noise filter removed; direction-first volatility entries, momentum exits and independent position trails active');}
function showPage(name){['dashboard','trades','history','logs'].forEach(p=>{const el=$(`page-${p}`);if(el)el.classList.toggle('active',p===name);const nav=$(`nav-${p}`);if(nav)nav.classList.toggle('active',p===name);});renderPageData();window.scrollTo({top:0,behavior:'smooth'});}
function renderTrades(){const el=$('tradesInfo');if(!el)return;if(!connection){el.innerHTML='<div class="empty">MetaApi is not connected.<br>Connect from Dashboard to view live trades.</div>';return;}const list=positionList();let html=`<div class="info-row"><span>Engine</span><b class="${trading?'green':''}">${trading?'RUNNING':'STOPPED'}</b></div><div class="info-row"><span>Connection</span><b>${synchronized?'CONNECTED':'SYNC REFRESH / RECONNECTING'}</b></div><div class="info-row"><span>Win rate</span><b class="green">${(tradeStats.wins+tradeStats.losses)>0?`${winRate().toFixed(1)}%`:'—'}</b></div><div class="info-row"><span>Wins / Losses</span><b>${tradeStats.wins} / ${tradeStats.losses}</b></div><div class="info-row"><span>Bias</span><b>${marketBias||'CALCULATING'}</b></div><div class="info-row"><span>State</span><b>${pullbackActive?'PULLBACK — WATCHING VOLATILITY':'DIRECTIONAL'}</b></div><div class="info-row"><span>Entry mode</span><b>LIVE VELOCITY EXPANSION</b></div><div class="info-row"><span>Open positions</span><b>${list.length}</b></div>`;if(!list.length)html+='<div class="empty">No open Pips-life positions.</div>';else list.forEach((p,i)=>{const id=idOf(p),stop=Number(positionStops.get(id)||p.stopLoss||0),trail=dynamicTrailPips(p,lastBid,lastAsk);html+=`<div class="info-row"><span>Position ${i+1} • ${sideOf(p)} • ${id.slice(0,8)}</span><b>${fmt(volumeOf(p))} LOT</b></div><div class="info-row"><span>Entry</span><b>${fmt(Number(p.openPrice))}</b></div><div class="info-row"><span>Individual trailing SL</span><b class="red">${stop>0?fmt(stop):'SETTING…'}</b></div><div class="info-row"><span>Active trail</span><b>${trail} PIPS</b></div>`;});el.innerHTML=html;}
function renderHistory(){const el=$('historyInfo');if(!el)return;if(!sessionHistory.length){el.innerHTML='<div class="empty">No completed bot events in this app session yet.</div>';return;}el.innerHTML=sessionHistory.slice(0,30).map(x=>`<div class="info-row"><span>${new Date(x.time).toLocaleTimeString()}</span><b>${x.text}</b></div>`).join('');}
function renderLogs(){const el=$('logsInfo');if(!el)return;el.innerHTML=eventLog.length?eventLog.map(x=>`<div class="log-row"><span class="log-time">${x.time.toLocaleTimeString()}</span>${String(x.text).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</div>`).join(''):'<div class="empty">No events yet.</div>';}
function renderPageData(){const list=positionList(),p=list[0]||null,s=p?Number(positionStops.get(idOf(p))||p.stopLoss||0):0;if($('sideBadge')){const side=p?sideOf(p):'';$('sideBadge').textContent=side||(list.length>1?`${list.length} OPEN`:lastDirection||'WAITING');$('sideBadge').classList.toggle('sell',side==='SELL');}if($('positionPrice'))$('positionPrice').textContent=p?fmt(Number(p.openPrice)):'—';if($('stopDetail'))$('stopDetail').textContent=s>0?fmt(s):'—';renderWinRate();renderTrades();renderHistory();renderLogs();}
ui.save.onclick=saveCredentials;ui.change.onclick=changeCredentials;ui.start.onclick=startBot;ui.stopBot.onclick=stopAllTrading;
$('nav-dashboard').onclick=()=>showPage('dashboard');$('nav-trades').onclick=()=>showPage('trades');$('nav-history').onclick=()=>showPage('history');$('nav-logs').onclick=()=>showPage('logs');
const androidToken=(()=>{try{return cleanToken(window.AndroidBot?.getSavedToken?.()||'');}catch(_){return '';}})();const androidAccount=(()=>{try{return String(window.AndroidBot?.getSavedAccountId?.()||'').trim();}catch(_){return '';}})();const savedToken=androidToken||cleanToken(localStorage.getItem('metaapi.token'));const savedAccount=androidAccount||String(localStorage.getItem('metaapi.accountId')||'').trim();if(savedToken&&savedAccount){localStorage.setItem('metaapi.token',savedToken);localStorage.setItem('metaapi.accountId',savedAccount);ui.token.value='SAVED TOKEN';ui.token.disabled=true;ui.account.value=savedAccount;addLog('Saved credentials found — reconnecting automatically');void connectSdk();}
addLog('Pips-life engine loaded — noise filter REMOVED; live velocity expansion enabled; MetaApi sync refreshes no longer stop trading; win rate tracking active');